name: es-check-version

on:
  workflow_run:
    workflows: ["tsc", "lint"]
    branches: [master]
    types:
      - completed


jobs:
  es-check-version:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: es-check-version
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: install node v12
          uses: actions/setup-node@v1
          with:
            node-version: 12
        - name: es-check-action
          uses: ali-kamalizade/es-check-action@1.0.2
          with:
              directory: 'dist/src'
              ecmaVersion: 'es5'
              files: '*.js'